/* eslint-disable */
export const CHANGE_AUTH = 'CHANGE_AUTH';
export const CHANGE_ALBUM = 'CHANGE_ALBUM';
export const CHANGE_ALBUMS = 'CHANGE_ALBUMS';
export const CHANGE_ARTISTAS = 'CHANGE_ARTISTAS';
export const CHANGE_ARTISTAS_ALBUM = 'CHANGE_ARTISTAS_ALBUM';
export const CHANGE_MUSICAS = 'CHANGE_MUSICAS';
export const CHANGE_MSG = 'CHANGE_MSG';
export const CHANGE_SEARCH = 'CHANGE_SEARCH';
